### ISSUE TITLE
Not specify the class property raises an error

### ISSUE THREAD

**Issue by Malian** [miguel-s/ex_heroicons#2]
The following code:
```html
<Heroicons.Components.Icon type="outline" name="academic-cap" />
```
raises the following error:
```console
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Surface.css_class/1
        (surface 0.4.0) lib/surface.ex:215: Surface.css_class(nil)
        (ex_heroicons 0.1.1) lib/heroicons/components/icon.ex:16: anonymous fn/2 in Heroicons.Components.Icon.render/1
```

**Comment by Malian** [comment]
Seems to be fixed on master!

**Comment by miguel-s** [comment]
@Malian published the fix
